repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]

    -   id: flake8
        args:
        - "--max-line-length=88"
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

    -   id: isort
        args:
        - "--profile"
        - "black"
        - "--filter-files"
        name: isort
        entry: isort
        require_serial: true
        language: python

# esses valores são locais, precisam das bibliotecas instaladas pelo pip no projeto.
